In [1]:
import numpy as np

In [2]:
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])


In [8]:
total=(female_completion+male_completion)
print (total)

[ 192.83205  205.28855  202.82258  186.63257  206.91115  196.29643
  204.70226  183.5571   185.67095  179.31151  198.43743  196.96855
  188.34567  234.67025  196.55129   66.08078   83.81045  181.92593
  114.16808  186.1203 ]


In [9]:
total/2

array([  96.416025,  102.644275,  101.41129 ,   93.316285,  103.455575,
         98.148215,  102.35113 ,   91.77855 ,   92.835475,   89.655755,
         99.218715,   98.484275,   94.172835,  117.335125,   98.275645,
         33.04039 ,   41.905225,   90.962965,   57.08404 ,   93.06015 ])

In [13]:
values = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])


In [15]:
def standardize_data(values):
    standardized_values = (values-values.mean())/values.std()
    return standardized_values

In [16]:
standardized_values = (values-values.mean())/values.std()


In [17]:
print (standardized_values)

[-0.31965231 -0.780123   -0.87650077  1.82207181 -0.03051941 -1.99019768
  0.30144772 -0.16973184  0.23719615  0.84758731  0.18365304  1.00821665
  0.87971351 -0.56595055 -1.07996476 -0.20185762  1.38301845 -0.03051941
  1.2545153  -1.87240259]


In [18]:
if True:
    a = np.array([1, 2, 3, 4])
    b = np.array([True, True, False, False])
    
    print (a[b])
    print (a[np.array([True, False, True, False])])


[1 2]
[1 3]


In [19]:
if True:
    a = np.array([1, 2, 3, 2, 1])
    b = (a >= 2)
    
    print (a[b])
    print (a[a >= 2])


[2 3 2]
[2 3 2]


In [20]:
if True:
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([1, 2, 3, 2, 1])
    
    print (b == 2)
    print (a[b == 2])


[False  True False  True False]
[2 4]


In [21]:
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])


In [22]:
total = time_spent.mean()
print (total)

37.9729979835


In [24]:
final_value = time_spent - time_spent.mean()
print (final_value)

[ -25.07602565  -37.97299798   26.57743419  -37.97299798  -13.74143648
    2.01862702  -37.97299798  -37.97299798  109.23383985  -37.97299798
  -37.97299798  -37.97299798    7.20961819  119.63154485   95.27046352
   14.87700969  -37.97299798   16.94748052  -11.19157381  -37.97299798]


In [25]:
print (time_spent[days_to_cancel>=7].mean())

41.0540034855


In [26]:
import pandas as pd

In [27]:
countries = ['Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
             'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
             'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia']

life_expectancy_values = [74.7,  75. ,  83.4,  57.6,  74.6,  75.4,  72.3,  81.5,  80.2,
                          70.3,  72.1,  76.4,  68.1,  75.2,  69.8,  79.4,  70.8,  62.7,
                          67.3,  70.6]

gdp_values = [ 1681.61390973,   2155.48523109,  21495.80508273,    562.98768478,
              13495.1274663 ,   9388.68852258,   1424.19056199,  24765.54890176,
              27036.48733192,   1945.63754911,  21721.61840978,  13373.21993972,
                483.97086804,   9783.98417323,   2253.46411147,  25034.66692293,
               3680.91642923,    366.04496652,   1175.92638695,   1132.21387981]



In [28]:
life_expectancy = pd.Series(life_expectancy_values)
gdp = pd.Series(gdp_values)


In [29]:
print (life_expectancy)

0     74.7
1     75.0
2     83.4
3     57.6
4     74.6
5     75.4
6     72.3
7     81.5
8     80.2
9     70.3
10    72.1
11    76.4
12    68.1
13    75.2
14    69.8
15    79.4
16    70.8
17    62.7
18    67.3
19    70.6
dtype: float64


In [30]:
print (gdp)


0      1681.613910
1      2155.485231
2     21495.805083
3       562.987685
4     13495.127466
5      9388.688523
6      1424.190562
7     24765.548902
8     27036.487332
9      1945.637549
10    21721.618410
11    13373.219940
12      483.970868
13     9783.984173
14     2253.464111
15    25034.666923
16     3680.916429
17      366.044967
18     1175.926387
19     1132.213880
dtype: float64


In [32]:
if True:
    print (life_expectancy[0])
    print (gdp[3:6])


74.7
3      562.987685
4    13495.127466
5     9388.688523
dtype: float64


In [33]:
if True:
    for country_life_expectancy in life_expectancy:
        print ('Examining life expectancy {}'.format(country_life_expectancy))


Examining life expectancy 74.7
Examining life expectancy 75.0
Examining life expectancy 83.4
Examining life expectancy 57.6
Examining life expectancy 74.6
Examining life expectancy 75.4
Examining life expectancy 72.3
Examining life expectancy 81.5
Examining life expectancy 80.2
Examining life expectancy 70.3
Examining life expectancy 72.1
Examining life expectancy 76.4
Examining life expectancy 68.1
Examining life expectancy 75.2
Examining life expectancy 69.8
Examining life expectancy 79.4
Examining life expectancy 70.8
Examining life expectancy 62.7
Examining life expectancy 67.3
Examining life expectancy 70.6


In [37]:
both_above  = (life_expectancy_values > life_expectancy_values.mean() &  gdp > gdp.mean())
print(both_above)

AttributeError: 'list' object has no attribute 'mean'

In [39]:
def variable(var1,var2):
    both_above = (var1 > var1.mean()) & \
                 (var2 > var2.mean())
    both_below = (var1 < var1.mean()) & \
                 (var2 < var2.mean())
    is_same = both_above | both_below
    num_same = is_same.sum()
    
    num_diff = len(var1)-num_same
    
    return (num_same,num_diff)


In [40]:
variable(life_expectancy,gdp)

(17, 3)

In [42]:
nap  = pd.Series([4,5,9,11],
        index = ['alabana',
                 'almoraf',
                 'buckysd',
                 'parislo'])


In [43]:
nap


alabana     4
almoraf     5
buckysd     9
parislo    11
dtype: int64

In [44]:
nap[0]

4

In [45]:
nap[0][0]

IndexError: invalid index to scalar variable.

In [46]:
nap[1]

5

In [47]:
nap.loc['buckysd']

9

In [48]:
nap.iloc[0]

4

In [49]:
nap.values

array([ 4,  5,  9, 11], dtype=int64)

In [50]:
nap.describe()

count     4.000000
mean      7.250000
std       3.304038
min       4.000000
25%       4.750000
50%       7.000000
75%       9.500000
max      11.000000
dtype: float64

In [51]:
countries = [
    'Afghanistan', 'Albania', 'Algeria', 'Angola',
    'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
    'Barbados', 'Belarus', 'Belgium', 'Belize',
    'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
]


In [52]:
employment_values = [
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076,
]


In [53]:
employment = pd.Series(employment_values, index=countries)


In [54]:
print (employment)

Afghanistan               55.700001
Albania                   51.400002
Algeria                   50.500000
Angola                    75.699997
Argentina                 58.400002
Armenia                   40.099998
Australia                 61.500000
Austria                   57.099998
Azerbaijan                60.900002
Bahamas                   66.599998
Bahrain                   60.400002
Bangladesh                68.099998
Barbados                  66.900002
Belarus                   53.400002
Belgium                   48.599998
Belize                    56.799999
Benin                     71.599998
Bhutan                    58.400002
Bolivia                   70.400002
Bosnia and Herzegovina    41.200001
dtype: float64


In [55]:
max_country = employment.idxmax()

In [56]:
print (max_country)

Angola


In [58]:
print (employment.argmax())

Angola


In [61]:
employment.loc['Angola']


75.699996949999999

In [62]:
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
    print (s1 + s2)


a    11
b    22
c    33
d    44
dtype: int64


In [63]:
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['b', 'd', 'a', 'c'])
    print (s1 + s2)


a    31
b    12
c    43
d    24
dtype: int64


In [71]:
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])
    val = s1.add(s2, fill_value=0)
    print (s1 + s2)


a     NaN
b     NaN
c    13.0
d    24.0
e     NaN
f     NaN
dtype: float64


In [66]:
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['e', 'f', 'g', 'h'])
    
    res = s1+s2
    print (s1 + s2)

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64


In [68]:
print(res.dropna())

Series([], dtype: float64)


In [70]:
print (val.dropna())

c    13.0
d    24.0
dtype: float64


In [72]:
print(val)

a     1.0
b     2.0
c    13.0
d    24.0
e    30.0
f    40.0
dtype: float64


In [74]:
s1.add(s2, fill_value=0)

a     1.0
b     2.0
c    13.0
d    24.0
e    30.0
f    40.0
dtype: float64

In [75]:
names = pd.Series([
    'Andre Agassi',
    'Barry Bonds',
    'Christopher Columbus',
    'Daniel Defoe',
    'Emilio Estevez',
    'Fred Flintstone',
    'Greta Garbo',
    'Humbert Humbert',
    'Ivan Ilych',
    'James Joyce',
    'Keira Knightley',
    'Lois Lane',
    'Mike Myers',
    'Nick Nolte',
    'Ozzy Osbourne',
    'Pablo Picasso',
    'Quirinus Quirrell',
    'Rachael Ray',
    'Susan Sarandon',
    'Tina Turner',
    'Ugueth Urbina',
    'Vince Vaughn',
    'Woodrow Wilson',
    'Yoji Yamada',
    'Zinedine Zidane'
])


In [77]:
if True:
    s = pd.Series([1, 2, 3, 4, 5])
    def add_one(x):
        return x + 1
    print (s.apply(add_one))

    

0    2
1    3
2    4
3    5
4    6
dtype: int64


In [86]:
def reverse_names(names):
    reverse = []
    for i in names:
        reverse.append(reverse(i))  
        print(reverse)    

In [81]:
import pandas as pd

In [90]:
def reverse_name(name):
    split_name = name.split(" ")
    first_name = split_name[0]
    last_name = split_name[1]
    return last_name + " " + first_name

In [91]:
reverse_name(names.iloc[0])

'Agassi Andre'

In [93]:
def reverse_name(name):
    split_name = name.split(" ")
    first_name = split_name[0]
    last_name = split_name[1]
    return last_name + " " + first_name

In [94]:
def reverse_names(names):
    return names.apply(reverse_name)

In [95]:
reverse_names(names)

0             Agassi Andre
1              Bonds Barry
2     Columbus Christopher
3             Defoe Daniel
4           Estevez Emilio
5          Flintstone Fred
6              Garbo Greta
7          Humbert Humbert
8               Ilych Ivan
9              Joyce James
10         Knightley Keira
11               Lane Lois
12              Myers Mike
13              Nolte Nick
14           Osbourne Ozzy
15           Picasso Pablo
16       Quirrell Quirinus
17             Ray Rachael
18          Sarandon Susan
19             Turner Tina
20           Urbina Ugueth
21            Vaughn Vince
22          Wilson Woodrow
23             Yamada Yoji
24         Zidane Zinedine
dtype: object

In [96]:
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])


In [101]:
mean0 = ridership[0,3]

In [102]:
mean0

5

In [103]:
len(ridership)

10

In [104]:
for i in range(0,10):
    val = ridership[i,0]
    pro = val.sum()
print(pro)   




1342


In [106]:
mean0 = pro/10

max_station = ridership[0,:].argmax()

In [108]:
max_station = ridership[0,:].argmax()
print(max_station)

3


In [110]:
mean_max = ridership[:,max_station].mean()
print(mean_max)

3239.9
